version: 2

env: &env
    environment:
      LC_ALL: "C.UTF-8"

    docker:
      - image: fpco/stack-build:lts

#-----------------------------------------------------------------------------
# Common utility stuff, not to be modified usually
#-----------------------------------------------------------------------------

preinstall: &preinstall
  run: |
      echo 'export PATH=/opt/cabal/bin:$PATH' >> $BASH_ENV
      source $BASH_ENV
      apt-get update

restore: &restore
  # Needs to happen after installing ca-certificates
  restore_cache:
    key: v1-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}

save: &save
  save_cache:
      key: v1-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
      paths:
        - ~/.cabal
        - ~/.ghc
        - ~/.local
        - ~/.stack

#-----------------------------------------------------------------------------
# Build matrix
#-----------------------------------------------------------------------------

jobs:
  cabal-ghc-8.6.3:
      <<: *env
      steps:
        - checkout
        - *preinstall
        - *restore
        - run: |
              apt-get install -y ghc-8.6.3
              apt-get install -y cabal-install-2.4
              cabal v2-update
              cabal v2-build --enable-tests --dependencies-only --project-file=cabal.project.ci -j2 all
              cabal v2-test --project-file=cabal.project.ci all
        - *save

  cabal-ghc-8.4.4:
      <<: *env
      steps:
        - checkout
        - *preinstall
        - *restore
        - run: |
              apt-get install -y ghc-8.4.4
              apt-get install -y cabal-install-2.4
              cabal v2-update
              cabal v2-build --enable-tests --dependencies-only --project-file=cabal.project.ci -j2 all
              cabal v2-test --project-file=cabal.project.ci all
        - *save
  cabal-ghc-8.2.2:
      <<: *env
      steps:
        - checkout
        - *preinstall
        - *restore
        - run: |
              apt-get install -y ghc-8.2.2
              apt-get install -y cabal-install-2.4
              cabal v2-update
              cabal v2-build --enable-tests --dependencies-only --project-file=cabal.project.ci -j2 all
              cabal v2-test --project-file=cabal.project.ci all
        - *save
  cabal-ghc-8.0.2:
      <<: *env
      steps:
        - checkout
        - *preinstall
        - *restore
        - run: |
              apt-get install -y ghc-8.0.2
              apt-get install -y cabal-install-2.4
              cabal v2-update
              cabal v2-build --enable-tests --dependencies-only --project-file=cabal.project.ci -j2 all
              cabal v2-test --project-file=cabal.project.ci all
        - *save
  cabal-ghc-7.10.3:
      <<: *env
      steps:
        - checkout
        - *preinstall
        - *restore
        - run: |
              apt-get install -y ghc-7.10.3
              apt-get install -y cabal-install-2.4
              cabal v2-update
              cabal v2-build --enable-tests --dependencies-only --project-file=cabal.project.ci -j2 all
              cabal v2-test --project-file=cabal.project.ci all
        - *save
  stack-ghc-8.6:
      <<: *env
      steps:
        - checkout
        - *preinstall
        - *restore
        - run: |
            apt-get install -y ghc-8.6.3
            stack update
            stack test --system-ghc --ghc-options='-O0 -Wall -Werror' .
        - *save

workflows:
  version: 2
  build:
    jobs:
      - cabal-ghc-8.6.3
      - cabal-ghc-8.4.4
      - cabal-ghc-8.2.2
      - cabal-ghc-8.0.2
      - cabal-ghc-7.10.3
      - stack-ghc-8.6
